language: javascript

services:
  - docker

jobs:
  include:
    - stage: docker hub auth
      script:
      - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - stage: build docker images, tag and publish to docker hub
      script:
      - docker build -t udagram-api-feed ./udagram-api-feed
      - docker build -t udagram-api-user ./udagram-api-user
      - docker build -t udagram-frontend ./udagram-frontend
      - docker build -t reverseproxy ./udagram-reverseproxy
      - docker tag udagram-api-feed elcharitas/udagram-api-feed:v1
      - docker tag udagram-api-user elcharitas/udagram-api-user:v1
      - docker tag udagram-frontend elcharitas/udagram-frontend:v1
      - docker tag reverseproxy elcharitas/reverseproxy:v1
      - docker push elcharitas/udagram-api-feed:v1
      - docker push elcharitas/udagram-api-user:v1
      - docker push elcharitas/udagram-frontend:v1
      - docker push elcharitas/reverseproxy:v1
