apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  selector:
    matchLabels:
      run: api-user
  replicas: 2
  template:
    metadata:
      labels:
        run: api-user
    spec:
      containers:
      - name: api-user
        image: elcharitas/udagram-api-user:v1
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: env-secrets
                key: POSTGRES_HOST
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: env-secrets
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-secrets
                key: POSTGRES_DB
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: env-secrets
                key: JWT_SECRET
        
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "500Mi"
        ports: 
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
