version: "3.3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: elcharitas/reverseproxy
  api_user:
    build:
      context: ./udagram-api-user
    image: elcharitas/udagram-api-user
  api_feed:
    build:
      context: ./udagram-api-feed
    image: elcharitas/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: elcharitas/udagram-frontend
